### ISSUE TITLE
Story - District Model Page

### ISSUE THREAD

**Issue by bzsinger** [WeTheSWEople/SWEThePeople#69]
Create a district model page that includes:
- [X] a grid of all parties
- [ ] at least three attributes for each district
- [X] links to each instance

**Time**
Estimated - 3hrs
Actual - 5.5hrs

**Comment by copperstick6** [comment]
We were kind of lost when it came to what we wanted to do for the District Models, we were teetering on making it a States page, because it was very tedious to find APIs for this page specifically. However, we managed to get it done. Next time, we can prepare better by getting the API research done beforehand.
